server:
  port: 8085

spring:
  application:
    name: test-ai-personality

logging:
  level:
    com.xdream: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"